#!/bin/sh
# the idea is to replace this w/https://github.com/Vanilla-OS/first-setup

if test -e "$HOME"/.config/adam-os/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

# setup/configure zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "10"

git clone https://github.com/AdamIsrael/dotfiles.git $HOME/.dotfiles && \
    rm -f $HOME/.zshrc && ln -s $HOME/.dotfiles/zshrc .zshrc && \
    rm -f $HOME/.aliases && ln -s $HOME/.dotfiles/aliases $HOME/.aliases &&
    rm -f $HOME/.bash_profile && ln -s $HOME/.dotfiles/bash_profile $HOME/.bash_profile && \
    rm -f $HOME/.gitconfig && ln -s $HOME/.dotfiles/gitconfig $HOME/.gitconfig && \
    rm -f $HOME/.vimrc && ln -s $HOME/.dotfiles/vimrc $HOME/.vimrc && \
    cd $HOME/.dotfiles && git submodule update --init --remote
    # ln -s $HOME/.dotfiles/zsh/plugins/zsh-syntax-highlighting
echo "20"


echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/adam-os/
touch "$HOME"/.config/adam-os/firstboot-done

) |

   zenity --progress --title="Adam-OS Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi